name: "Lychee Broken Link Checker (fork/test)"
description: "Quickly check links in Markdown, HTML, and text files"
inputs:
  args:
    description: "lychee arguments"
    default: "--verbose --no-progress *.md"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "external-link"
  color: "purple"
